# Generated by Django 3.2 on 2021-10-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='考试时间'),
        ),
    ]
