# -*- coding: utf-8 -*-

from scrapy.item import Item, Field


class ZhaopinCrawlerItem(Item):
    _id = Field()
    _ch = Field()
    _key = Field()
    _spec = Field()
    _dcm = Field()
    _adp = Field()
    lang = Field()
    tags = Field()
    publish_time = Field()
    update_time = Field()
    gather_time = Field()
    insert_time = Field()
    url = Field()
    site_id = Field()
    site_name = Field()
    job_name = Field()
    job_salary = Field()
    job_education = Field()
    job_number = Field()
    job_date_range = Field()
    job_description = Field()
    job_description_raw = Field()
    job_department = Field()
    job_address = Field()
    job_experience = Field()
    job_recruiter = Field()
    job_recruiter_position = Field()
    job_advantage = Field()
    company_name = Field()
    company_home_url = Field()
    company_logo = Field()
    company_industry = Field()
    company_development_stage = Field()
    company_scale = Field()
    company_description = Field()
    company_business_info = Field()
    extra_info = Field()
