# -*- coding: utf-8 -*-

import time


class DefaultValuesPipeline(object):
    def process_item(self, item, spider):
        current_time = int(time.time() * 1000)
        item.setdefault("_id", "")
        item.setdefault("_ch", 0)
        item.setdefault("_key", "")
        item.setdefault("_spec", "")
        item.setdefault("_dcm", "")
        item.setdefault("_adp", "")
        item.setdefault("lang", "")
        item.setdefault("tags", [])
        item.setdefault("publish_time", current_time)
        item.setdefault("update_time", current_time)
        item.setdefault("gather_time", current_time)
        item.setdefault("insert_time", current_time)
        item.setdefault("url", "")
        item.setdefault("site_id", 0)
        item.setdefault("site_name", "")
        item.setdefault("job_name", "")
        item.setdefault("job_salary", "")
        item.setdefault("job_education", "")
        item.setdefault("job_number", "")
        item.setdefault("job_date_range", "")
        item.setdefault("job_description", "")
        item.setdefault("job_description_raw", "")
        item.setdefault("job_department", "")
        item.setdefault("job_address", "")
        item.setdefault("job_experience", "")
        item.setdefault("job_recruiter", "")
        item.setdefault("job_recruiter_position", "")
        item.setdefault("job_advantage", "")
        item.setdefault("company_name", "")
        item.setdefault("company_home_url", "")
        item.setdefault("company_logo", "")
        item.setdefault("company_industry", "")
        item.setdefault("company_development_stage", "")
        item.setdefault("company_scale", "")
        item.setdefault("company_description", "")
        item.setdefault("company_business_info", "")
        item.setdefault("extra_info", "")
