# -*- coding: utf-8 -*-
import scrapy
class CasTravelItem(scrapy.Item):
  DID = scrapy.Field()
  CasTravelNo = scrapy.Field() #派车单号
  BwfTravelNo = scrapy.Field() # bwf管理序号
  Status = scrapy.Field() #状态：待派车，已派车，活动中，取消，异常 已完成
  ApplyStatus = scrapy.Field()    # 申请状态类型：新申请，变更申请，注销申请
  BwfStatus = scrapy.Field()     # bwf状态：未完成，完成，退回，取消
  Cseating = scrapy.Field()    # 人数
  AcutalUser = scrapy.Field()     # 实际使用者
  InSideLine= scrapy.Field()    # 内线
  FlightNo = scrapy.Field()    # 车次/航班编号
  OstartTime = scrapy.Field()    # 出发时间
  ReturnTime = scrapy.Field()    # 返回时间
  FlightTime = scrapy.Field()    # 开车/起飞到达时间
  ChangeReson = scrapy.Field()    # 变更取消理由
  UseDate = scrapy.Field()    # 用车日期
  CarType = scrapy.Field()    # 用车类型
  UseReson = scrapy.Field()    # 用车理由
  DetailedAddress = scrapy.Field()    # 行程详细地址
  Company = scrapy.Field()    # 公司
  CostDepartment = scrapy.Field()    # 经费负担部门
  ShareCore = scrapy.Field()    # 经费负担代码
  CreateID = scrapy.Field()  
  CreateDate = scrapy.Field()  
  ModifyDate = scrapy.Field()  
  ModifyID = scrapy.Field()  
  Enables = scrapy.Field()    # 是否可用：用于计算分摊标志
  PhonePassenger = scrapy.Field()    # 乘客和联系电话：用josn保存
  applyperson = scrapy.Field()    # 申请人
  applyDate = scrapy.Field()    # 申请日期
  MergeCode = scrapy.Field()    # 合并代码
  ApprovalData = scrapy.Field()    # 审批信息
  CasDriverDID = scrapy.Field()    # 司机model关联ID
  CasBusinessCarDID = scrapy.Field()    # 车辆model关联id
  cqf = scrapy.Field()    # 路桥费
  Kilometers = scrapy.Field()    # 总公里数
  Remark = scrapy.Field()    # 备注
  TotalUseTime  = scrapy.Field()    # 行程总用时
  Types  = scrapy.Field()    # 类型：多日期行程的类型
  ParentID= scrapy.Field()    